{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 필요한 라이브러리 불러오기\n",
    "\n",
    "from konlpy.tag import Mecab \n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "# mecab 실행\n",
    "\n",
    "mecab = Mecab(dicpath=r\"C:\\Mecab\\mecab-ko-dic\") # dictation path 설정 / mecab-ko-dic이 mecab의 단어사전임"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "mecab2 = Mecab(dicpath=r\"C:\\Mecab2\\mecab-ko-dic\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['해운물류기업', '해운물류', '분야', '취업', '희망', '구직자', '참여', '채용정보', '교류', '연계', '취업', '지원', '제도']\n",
      "['해운', '물류', '기업', '해운', '물류', '분야', '취업', '희망', '구직자', '참여', '채용', '정보', '교류', '연계', '취업', '지원', '제도']\n"
     ]
    }
   ],
   "source": [
    "print(mecab1.nouns('해운물류기업과 해운물류 분야 취업을 희망하는 구직자가 참여하여 채용정보를 교류하고, 연계 취업을 지원하는 제도'))\n",
    "print(mecab2.nouns('해운물류기업과 해운물류 분야 취업을 희망하는 구직자가 참여하여 채용정보를 교류하고, 연계 취업을 지원하는 제도'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 형태소 분석할 데이터 준비 - 정책 내용 데이터 불러오기 \n",
    "\n",
    "content = pd.read_csv('using_data/policy_content.csv', encoding = 'euc-kr')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>index</th>\n",
       "      <th>name</th>\n",
       "      <th>description</th>\n",
       "      <th>content</th>\n",
       "      <th>URL</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0</td>\n",
       "      <td>국민취업지원제도</td>\n",
       "      <td>한국형 실업부조로 고용안전망 사각지대에 있는 취업취약계층에게 취업지원서비스 및 생활...</td>\n",
       "      <td>1. 취업취약계층에 취업지원\\n- 취업지원서비스를 종합적으로 제공하고, 저소득 구직...</td>\n",
       "      <td>https://www.youthcenter.go.kr/youngPlcyUnif/yo...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>청년추가고용장려금 지원사업</td>\n",
       "      <td>청년을 정규직으로 추가로 고용한 중소?중견기업에 인건비를 지원함으로써, 양질의 청년...</td>\n",
       "      <td>1. 청년 추가채용 1명당 연 최대 900만원을 3년간 지원2. 고용위기 지역 지정...</td>\n",
       "      <td>https://www.youthcenter.go.kr/youngPlcyUnif/yo...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>국민내일배움카드</td>\n",
       "      <td>국민 누구나 일자리에 도움이 되는 훈련을 받을 수 있는 평생능력개발 기반 마련을 위...</td>\n",
       "      <td>1. 국민 누구나 국민내일배움카드 신청 가능\\n- 분리 운영되었던 실업자/재직자 내...</td>\n",
       "      <td>https://www.youthcenter.go.kr/youngPlcyUnif/yo...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>청년내일채움공제</td>\n",
       "      <td>중소·중견기업 청년 근로자의 장기근속과 자산형성을 지원하기 위해 청년, 기업, 정부...</td>\n",
       "      <td>1. 청년 지원내용\\n - 청년 본인이 2년간 300만원(매월 12만 5천원)을 적...</td>\n",
       "      <td>https://www.youthcenter.go.kr/youngPlcyUnif/yo...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>청년고용지원</td>\n",
       "      <td>청년고용정책 지원</td>\n",
       "      <td>1. 지원내용 청년고용정책 심층 모니터링, 대학일자리센터 컨설팅 및 운영지원, 청년...</td>\n",
       "      <td>https://www.youthcenter.go.kr/youngPlcyUnif/yo...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   index            name                                        description  \\\n",
       "0      0        국민취업지원제도  한국형 실업부조로 고용안전망 사각지대에 있는 취업취약계층에게 취업지원서비스 및 생활...   \n",
       "1      1  청년추가고용장려금 지원사업  청년을 정규직으로 추가로 고용한 중소?중견기업에 인건비를 지원함으로써, 양질의 청년...   \n",
       "2      3        국민내일배움카드  국민 누구나 일자리에 도움이 되는 훈련을 받을 수 있는 평생능력개발 기반 마련을 위...   \n",
       "3      4        청년내일채움공제  중소·중견기업 청년 근로자의 장기근속과 자산형성을 지원하기 위해 청년, 기업, 정부...   \n",
       "4      5          청년고용지원                                          청년고용정책 지원   \n",
       "\n",
       "                                             content  \\\n",
       "0  1. 취업취약계층에 취업지원\\n- 취업지원서비스를 종합적으로 제공하고, 저소득 구직...   \n",
       "1  1. 청년 추가채용 1명당 연 최대 900만원을 3년간 지원2. 고용위기 지역 지정...   \n",
       "2  1. 국민 누구나 국민내일배움카드 신청 가능\\n- 분리 운영되었던 실업자/재직자 내...   \n",
       "3  1. 청년 지원내용\\n - 청년 본인이 2년간 300만원(매월 12만 5천원)을 적...   \n",
       "4  1. 지원내용 청년고용정책 심층 모니터링, 대학일자리센터 컨설팅 및 운영지원, 청년...   \n",
       "\n",
       "                                                 URL  \n",
       "0  https://www.youthcenter.go.kr/youngPlcyUnif/yo...  \n",
       "1  https://www.youthcenter.go.kr/youngPlcyUnif/yo...  \n",
       "2  https://www.youthcenter.go.kr/youngPlcyUnif/yo...  \n",
       "3  https://www.youthcenter.go.kr/youngPlcyUnif/yo...  \n",
       "4  https://www.youthcenter.go.kr/youngPlcyUnif/yo...  "
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "content.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### nouns_list  \n",
    "' description ' 에서 형태소 분석처리한 모든 단어 모음 (리스트)  \n",
    "' description ' 의 모든 단어를 다 보고 싶을 때 사용\n",
    "     \n",
    "     \n",
    "#### policy_nouns  \n",
    "' 한 정책 ' 의 인덱스 + 형태소 분석처리한 단어 리스트의 모음 (리스트) (DF)  \n",
    "' 한 정책 ' 에 어떤 단어가 들어있는지 볼 때 사용  \n",
    "  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "nouns_list = []\n",
    "policy_index = []\n",
    "policy_nouns = []\n",
    "\n",
    "for i in range(len(content['description'])):\n",
    "    nouns_list.extend(mecab.nouns(content['description'][i]))\n",
    "    policy_index.append(content['index'][i])\n",
    "    policy_nouns.append(mecab.nouns(content['description'][i]))\n",
    "\n",
    "policy_nouns = pd.DataFrame({'index': policy_index,\n",
    "                             'nouns': policy_nouns})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "7"
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "policy_nouns['nouns'][0].index('지원')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>index</th>\n",
       "      <th>nouns</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0</td>\n",
       "      <td>[한국형, 실업부조, 고용안전망, 사각지대, 취업취약계층, 취업지원서비스, 생활안정...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>[청년, 정규직, 추가, 고용, 중소, 중견기업, 인건비, 지원, 양질, 청년, 일...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>[국민, 누구, 일자리, 도움, 훈련, 수, 평생능력개발, 기반, 마련, 정책, 기...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>[중소, 중견기업, 청년, 근로자, 장기근속, 자산형성, 지원, 청년, 기업, 정부...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>[청년고용정책, 지원]</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>995</th>\n",
       "      <td>3066</td>\n",
       "      <td>[취업, 도움, 필요, 분, 자신, 이해, 긍정적, 측면, 자신감, 회복, 자기, ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>996</th>\n",
       "      <td>3068</td>\n",
       "      <td>[나, 직업, 고민, 분과, 분주, 발걸음, 일자리, 구직자, 프로그램]</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>997</th>\n",
       "      <td>3069</td>\n",
       "      <td>[자활사업, 참여, 근로능력, 기초생활, 수급자, 대상, 맞춤형, 취업지원, 프로그램]</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>998</th>\n",
       "      <td>3070</td>\n",
       "      <td>[취업, 자신, 직업, 고민, 청년, 청년직업지도, 프로그램]</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>999</th>\n",
       "      <td>3072</td>\n",
       "      <td>[고교졸업, 예정, 취업희망자, 학력, 청년층, 직장, 원활, 진입, 성공적, 적응...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1000 rows × 2 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     index                                              nouns\n",
       "0        0  [한국형, 실업부조, 고용안전망, 사각지대, 취업취약계층, 취업지원서비스, 생활안정...\n",
       "1        1  [청년, 정규직, 추가, 고용, 중소, 중견기업, 인건비, 지원, 양질, 청년, 일...\n",
       "2        3  [국민, 누구, 일자리, 도움, 훈련, 수, 평생능력개발, 기반, 마련, 정책, 기...\n",
       "3        4  [중소, 중견기업, 청년, 근로자, 장기근속, 자산형성, 지원, 청년, 기업, 정부...\n",
       "4        5                                       [청년고용정책, 지원]\n",
       "..     ...                                                ...\n",
       "995   3066  [취업, 도움, 필요, 분, 자신, 이해, 긍정적, 측면, 자신감, 회복, 자기, ...\n",
       "996   3068           [나, 직업, 고민, 분과, 분주, 발걸음, 일자리, 구직자, 프로그램]\n",
       "997   3069   [자활사업, 참여, 근로능력, 기초생활, 수급자, 대상, 맞춤형, 취업지원, 프로그램]\n",
       "998   3070                 [취업, 자신, 직업, 고민, 청년, 청년직업지도, 프로그램]\n",
       "999   3072  [고교졸업, 예정, 취업희망자, 학력, 청년층, 직장, 원활, 진입, 성공적, 적응...\n",
       "\n",
       "[1000 rows x 2 columns]"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "policy_nouns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 검색단어와 앞, 뒤 2단어를 추출하여 살펴보기"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>index</th>\n",
       "      <th>words</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0</td>\n",
       "      <td>[취업지원서비스, 생활안정, 지원, 정책]</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>[중견기업, 인건비, 지원, 양질, 청년]</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>[훈련비, 등, 지원]</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>[장기근속, 자산형성, 지원, 청년, 기업]</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>[청년고용정책, 지원]</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>415</th>\n",
       "      <td>3060</td>\n",
       "      <td>[인턴근무, 취업알선, 지원, 제도]</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>416</th>\n",
       "      <td>3061</td>\n",
       "      <td>[취업처, 알선, 지원, 제도]</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>417</th>\n",
       "      <td>3062</td>\n",
       "      <td>[청년근로자, 인건비, 지원, 교통복지비용, 주거정착금]</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>418</th>\n",
       "      <td>3063</td>\n",
       "      <td>[수요기반, 인력양성, 지원, 제도]</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>419</th>\n",
       "      <td>3072</td>\n",
       "      <td>[적응, 수, 지원, 취업지원, 프로그램]</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>420 rows × 2 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     index                            words\n",
       "0        0          [취업지원서비스, 생활안정, 지원, 정책]\n",
       "1        1          [중견기업, 인건비, 지원, 양질, 청년]\n",
       "2        3                     [훈련비, 등, 지원]\n",
       "3        4         [장기근속, 자산형성, 지원, 청년, 기업]\n",
       "4        5                     [청년고용정책, 지원]\n",
       "..     ...                              ...\n",
       "415   3060             [인턴근무, 취업알선, 지원, 제도]\n",
       "416   3061                [취업처, 알선, 지원, 제도]\n",
       "417   3062  [청년근로자, 인건비, 지원, 교통복지비용, 주거정착금]\n",
       "418   3063             [수요기반, 인력양성, 지원, 제도]\n",
       "419   3072          [적응, 수, 지원, 취업지원, 프로그램]\n",
       "\n",
       "[420 rows x 2 columns]"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "index_num = []\n",
    "front_back_list = []\n",
    "\n",
    "###### 단어를 입력하시오.##########\n",
    "word = '지원'\n",
    "###################################\n",
    "\n",
    "for i in range(len(policy_nouns)):\n",
    "    \n",
    "    # 정책 리스트에 이 단어가 있으면\n",
    "    if word in policy_nouns['nouns'][i]:\n",
    "        \n",
    "        # 검색단어가 제일 첫번째 순서면 실행\n",
    "        if policy_nouns['nouns'][i].index(word) == 0:\n",
    "            index_num.append(policy_nouns['index'][i])\n",
    "            front_back_list.append(policy_nouns['nouns'][i][:3]) # 검색단어 + 뒷2단어\n",
    "            \n",
    "        # 검색단어가 두번째 순서면 실행    \n",
    "        elif policy_nouns['nouns'][i].index(word) == 1:\n",
    "            index_num.append(policy_nouns['index'][i])\n",
    "            front_back_list.append(policy_nouns['nouns'][i][0:4])\n",
    "            \n",
    "        else:\n",
    "            index_num.append(policy_nouns['index'][i])\n",
    "            front_back_list.append(policy_nouns['nouns'][i][policy_nouns['nouns'][i].index(word)-2:policy_nouns['nouns'][i].index(word)+3])\n",
    "\n",
    "df = pd.DataFrame()\n",
    "df['index'] = index_num\n",
    "df['words'] = front_back_list\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "pd.reset_option('display.max_rows',None)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 한 글자로 이루어진 단어 추출"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>word</th>\n",
       "      <th>cnt</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>청년</td>\n",
       "      <td>553</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>지원</td>\n",
       "      <td>462</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>64</th>\n",
       "      <td>제공</td>\n",
       "      <td>314</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>등</td>\n",
       "      <td>200</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>취업</td>\n",
       "      <td>192</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>577</th>\n",
       "      <td>호소</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>576</th>\n",
       "      <td>사</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>570</th>\n",
       "      <td>초청</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>566</th>\n",
       "      <td>학내</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>921</th>\n",
       "      <td>분주</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>922 rows × 2 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "    word  cnt\n",
       "2     청년  553\n",
       "0     지원  462\n",
       "64    제공  314\n",
       "23     등  200\n",
       "34    취업  192\n",
       "..   ...  ...\n",
       "577   호소    1\n",
       "576    사    1\n",
       "570   초청    1\n",
       "566   학내    1\n",
       "921   분주    1\n",
       "\n",
       "[922 rows x 2 columns]"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "one_word = [i for i in nouns_list if len(i) <= 2]\n",
    "\n",
    "from collections import Counter\n",
    "\n",
    "cnt_rank = pd.DataFrame()\n",
    "\n",
    "cnt_rank['word'] = pd.Series(list(dict(Counter(one_word)).keys()))\n",
    "cnt_rank['cnt'] = pd.Series(list(dict(Counter(one_word)).values()))\n",
    "\n",
    "cnt_rank.sort_values(by='cnt', ascending = False)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "###  모든 단어들의 빈도수 추출"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 80,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>description_word</th>\n",
       "      <th>cnt</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>한국형</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1735</th>\n",
       "      <td>드론방제</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1736</th>\n",
       "      <td>현장인턴</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1737</th>\n",
       "      <td>충북전략산업</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1739</th>\n",
       "      <td>성장기반</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>39</th>\n",
       "      <td>등</td>\n",
       "      <td>200</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>일자리</td>\n",
       "      <td>228</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>108</th>\n",
       "      <td>제공</td>\n",
       "      <td>314</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>지원</td>\n",
       "      <td>462</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>청년</td>\n",
       "      <td>553</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>2657 rows × 2 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     description_word  cnt\n",
       "0                 한국형    1\n",
       "1735             드론방제    1\n",
       "1736             현장인턴    1\n",
       "1737           충북전략산업    1\n",
       "1739             성장기반    1\n",
       "...               ...  ...\n",
       "39                  등  200\n",
       "17                일자리  228\n",
       "108                제공  314\n",
       "7                  지원  462\n",
       "9                  청년  553\n",
       "\n",
       "[2657 rows x 2 columns]"
      ]
     },
     "execution_count": 80,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from collections import Counter\n",
    "\n",
    "cnt_rank = pd.DataFrame()\n",
    "\n",
    "cnt_rank['description_word'] = pd.Series(list(dict(Counter(nouns_list)).keys()))\n",
    "cnt_rank['cnt'] = pd.Series(list(dict(Counter(nouns_list)).values()))\n",
    "\n",
    "cnt_rank.sort_values(by='cnt', ascending = True) # 내림차순으로 정렬"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 83,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>description_word</th>\n",
       "      <th>cnt</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "Empty DataFrame\n",
       "Columns: [description_word, cnt]\n",
       "Index: []"
      ]
     },
     "execution_count": 83,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "cnt_rank.loc[cnt_rank['description_word']=='물류']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>word</th>\n",
       "      <th>cnt</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>청년</td>\n",
       "      <td>553</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>지원</td>\n",
       "      <td>462</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>94</th>\n",
       "      <td>제공</td>\n",
       "      <td>314</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>일자리</td>\n",
       "      <td>228</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>57</th>\n",
       "      <td>취업</td>\n",
       "      <td>192</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1338</th>\n",
       "      <td>인턴기회</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1336</th>\n",
       "      <td>신규고용</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1334</th>\n",
       "      <td>부산협의회</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1333</th>\n",
       "      <td>코리아스타트포럼</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2552</th>\n",
       "      <td>기초생활</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>2553 rows × 2 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "          word  cnt\n",
       "9           청년  553\n",
       "7           지원  462\n",
       "94          제공  314\n",
       "17         일자리  228\n",
       "57          취업  192\n",
       "...        ...  ...\n",
       "1338      인턴기회    1\n",
       "1336      신규고용    1\n",
       "1334     부산협의회    1\n",
       "1333  코리아스타트포럼    1\n",
       "2552      기초생활    1\n",
       "\n",
       "[2553 rows x 2 columns]"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "one_word = [i for i in nouns_list if len(i) > 1]\n",
    "\n",
    "from collections import Counter\n",
    "\n",
    "cnt_rank = pd.DataFrame()\n",
    "\n",
    "cnt_rank['word'] = pd.Series(list(dict(Counter(one_word)).keys()))\n",
    "cnt_rank['cnt'] = pd.Series(list(dict(Counter(one_word)).values()))\n",
    "\n",
    "cnt_rank.sort_values(by='cnt', ascending = False)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 단순하게 빈도수로 테스트"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "물류, 유통 분야에 취업을 희망하는데 관련된 직무 교육 사업이 있나요?\n"
     ]
    }
   ],
   "source": [
    "# 사용자 글 입력\n",
    "text = input()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['물류', '유통', '분야', '취업', '희망', '관련', '직무', '교육', '사업']"
      ]
     },
     "execution_count": 61,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "words = [i for i in mecab.nouns(text) if len(i) > 1]\n",
    "words"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>score</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>912</th>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>65</th>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>784</th>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>415</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>416</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>417</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>419</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>999</th>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1000 rows × 1 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     score\n",
       "912      4\n",
       "65       4\n",
       "784      4\n",
       "14       3\n",
       "11       3\n",
       "..     ...\n",
       "415      0\n",
       "416      0\n",
       "417      0\n",
       "419      0\n",
       "999      0\n",
       "\n",
       "[1000 rows x 1 columns]"
      ]
     },
     "execution_count": 62,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "score_list = []\n",
    "\n",
    "for i in policy_nouns['nouns']:\n",
    "    score = 0\n",
    "    for j in words:\n",
    "        if j in i:\n",
    "            score += 1\n",
    "    score_list.append(score)\n",
    "\n",
    "example = pd.DataFrame()\n",
    "example['score'] = score_list\n",
    "\n",
    "example.sort_values(by='score', ascending = False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>index</th>\n",
       "      <th>name</th>\n",
       "      <th>description</th>\n",
       "      <th>content</th>\n",
       "      <th>URL</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>65</th>\n",
       "      <td>69</td>\n",
       "      <td>데이터 청년 캠퍼스(빅데이터 청년인재 양성 및 일자리 연계)</td>\n",
       "      <td>빅데이터 기술을 선도하는 국내 최고의 대학이 기업 수요에 부응하는 실무 중심의 교육을 실시하고, 한국데이터산업진흥원과 관련 기업이 빅데이터 직무 취업을 지원하는 데이터 융합 인재 양성 프로그램</td>\n",
       "      <td>전액 정부 지원 프로그램*\\n*빅데이터 전문교육: 온라인교육(3주), 이론실습교육(데이터 관련 전공 대학생 4주/ 석박사 대학원생 6주), 파일럿 프로젝트(데이터 관련 전공 대학생 6주/ 석박사 대학원생 4주), 수료식 및 시상\\n\\n- 교육비 전액 지원, 맞춤형 채용 정보 제공, 취업 클리닉, 대학별 우수 프로젝트 선정 및 시상, 전문가 자격증 취득 지원, 채용박람회 개최</td>\n",
       "      <td>https://www.youthcenter.go.kr/youngPlcyUnif/youngPlcyUnifList.do</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>784</th>\n",
       "      <td>1020</td>\n",
       "      <td>고교취업 활성화\\n</td>\n",
       "      <td>경기도내 특성화고, 마이스터고, 종합고 등 재학생을 대상으로 취업에 필요한 직무 교육을 제공하여 취업역량을 강화하고, 취업 노하우 공유를 통해 조기 취업에 필요한 다양한 사업을 진행하고 있습니다.</td>\n",
       "      <td>취업 관련 직무교육 실시 및 자격증 취득 지원\\n이력서 작성, 면접스킬 향상 등 취업 역량강화 과정 지원\\n학교별 우수 취업 선배와 재학생 간 취업멘토링 실시 지원</td>\n",
       "      <td>https://youth.gg.go.kr/site/main/archive/policy/youth_policy/89</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>912</th>\n",
       "      <td>2072</td>\n",
       "      <td>2021 [전북 식품산업 고용성장 패키지] 산업간 전직지원 교육생 모집</td>\n",
       "      <td>식품기업으로 취업 희망하는 전북도민 교육 사업</td>\n",
       "      <td>식품 전직과정 운영 / 무료 지원 / 교육실비 지급 / 수료증 발급 / 채용연계</td>\n",
       "      <td>jb2038.or.kr</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "     index                                     name  \\\n",
       "65      69        데이터 청년 캠퍼스(빅데이터 청년인재 양성 및 일자리 연계)   \n",
       "784   1020                               고교취업 활성화\\n   \n",
       "912   2072  2021 [전북 식품산업 고용성장 패키지] 산업간 전직지원 교육생 모집   \n",
       "\n",
       "                                                                                                       description  \\\n",
       "65     빅데이터 기술을 선도하는 국내 최고의 대학이 기업 수요에 부응하는 실무 중심의 교육을 실시하고, 한국데이터산업진흥원과 관련 기업이 빅데이터 직무 취업을 지원하는 데이터 융합 인재 양성 프로그램   \n",
       "784  경기도내 특성화고, 마이스터고, 종합고 등 재학생을 대상으로 취업에 필요한 직무 교육을 제공하여 취업역량을 강화하고, 취업 노하우 공유를 통해 조기 취업에 필요한 다양한 사업을 진행하고 있습니다.   \n",
       "912                                                                                      식품기업으로 취업 희망하는 전북도민 교육 사업   \n",
       "\n",
       "                                                                                                                                                                                                                content  \\\n",
       "65   전액 정부 지원 프로그램*\\n*빅데이터 전문교육: 온라인교육(3주), 이론실습교육(데이터 관련 전공 대학생 4주/ 석박사 대학원생 6주), 파일럿 프로젝트(데이터 관련 전공 대학생 6주/ 석박사 대학원생 4주), 수료식 및 시상\\n\\n- 교육비 전액 지원, 맞춤형 채용 정보 제공, 취업 클리닉, 대학별 우수 프로젝트 선정 및 시상, 전문가 자격증 취득 지원, 채용박람회 개최   \n",
       "784                                                                                                                         취업 관련 직무교육 실시 및 자격증 취득 지원\\n이력서 작성, 면접스킬 향상 등 취업 역량강화 과정 지원\\n학교별 우수 취업 선배와 재학생 간 취업멘토링 실시 지원   \n",
       "912                                                                                                                                                                        식품 전직과정 운영 / 무료 지원 / 교육실비 지급 / 수료증 발급 / 채용연계   \n",
       "\n",
       "                                                                  URL  \n",
       "65   https://www.youthcenter.go.kr/youngPlcyUnif/youngPlcyUnifList.do  \n",
       "784   https://youth.gg.go.kr/site/main/archive/policy/youth_policy/89  \n",
       "912                                                      jb2038.or.kr  "
      ]
     },
     "execution_count": 63,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "content.iloc[example.loc[example['score']  ==  max(example['score'])].index]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 64,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['해운',\n",
       " '물류',\n",
       " '기업',\n",
       " '해운',\n",
       " '물류',\n",
       " '분야',\n",
       " '취업',\n",
       " '희망',\n",
       " '구직자',\n",
       " '참여',\n",
       " '채용',\n",
       " '정보',\n",
       " '교류',\n",
       " '연계',\n",
       " '취업',\n",
       " '지원',\n",
       " '제도']"
      ]
     },
     "execution_count": 64,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "mecab.nouns(content.loc[content['index']==1027]['description'].iloc[0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 79,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'해운물류기업과 해운물류 분야 취업을 희망하는 구직자가 참여하여 채용정보를 교류하고, 연계 취업을 지원하는 제도입니다.'"
      ]
     },
     "execution_count": 79,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "content.loc[content['index']==1027]['description'].iloc[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "metadata": {},
   "outputs": [],
   "source": [
    "pd.options.display.max_colwidth = 2000"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
